### ISSUE TITLE
Write a custom django-admin management command 

### ISSUE THREAD

**Issue by raquel-ucl** [womenhackfornonprofits/fashion-revolution-django#13]
This would be needed by the front end in order to store the latest X tweets in the DB every few minutes.

**Comment by raquel-ucl** [comment]
Looking at this [docu](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/).
Pushing changes to the `twitter_client/tidy_up branch`.

**Comment by raquel-ucl** [comment]
Done a first version of it that is used as:

```
python manage.py get_tweets
```

Will keep on working on it to grab input parameters like hashtag and since time.

**Comment by raquel-ucl** [comment]
It won't grab since time, because it gets it from the DB, but it'd be nice for it to get the hashtag from the command line. At the moment it's hardcoded.

**Comment by lili2311** [comment]
can close?

**Comment by raquel-ucl** [comment]
Let's leave it hardcoded, otherwise this'll never get done :)
