### ISSUE TITLE
Database Restrictions [Django]

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/fashion-revolution-django#22]
_From @lili2311 on April 5, 2016 18:59_

- [x]  Database must be Postgresql because of Heroku
- [ ]  Max image urls we can store for free is 10k, so let's only store the latest 10k. Delete the older ones.

_Copied from original issue: womenhackfornonprofits/fashion-revolution#7_

**Comment by lili2311** [comment]
DB is set to be Postgress in this [PR](https://github.com/womenhackfornonprofits/fashion-revolution-django/pull/1)

**Comment by marizoldi** [comment]
Latest TwitterClient.py uploaded on 10K_limit branch. Need still to refresh ID for it to work properly. Please review

**Comment by lili2311** [comment]
https://github.com/womenhackfornonprofits/fashion-revolution-django/pull/40
https://github.com/womenhackfornonprofits/fashion-revolution-django/pull/41
