### ISSUE TITLE
Integrate Twitter Client app into Django

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/fashion-revolution-django#25]
_From @lili2311 on April 5, 2016 18:49_

Twitter Client should be able to:

- [x] pull in tweet **Image URL ** and **User Name** -> save to Django DB [DONE]
- [x] pull in the info frequently, every x number of minutes/hours etc [will create a django management command]
- [ ] pull in tweets **retweeted by a specially created user** that have a hashtag **#FashRevWall** [not required right now]

_Copied from original issue: womenhackfornonprofits/fashion-revolution#3_

**Comment by lili2311** [comment]
[PR](https://github.com/womenhackfornonprofits/fashion-revolution-django/pull/12)

**Comment by marizoldi** [comment]
We need to get the 'published_at' time of Tweets

**Comment by raquel-ucl** [comment]
I thought it was `created_at`. If it's `created_at`, that is already being done, but awaiting Lili's code review in PR #28.

**Comment by marizoldi** [comment]
Probably created_at is correct. I cannot find their difference..

**Comment by raquel-ucl** [comment]
PR #28 merged :)
